//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalHealth.MhrFhirClient {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MhrFhirClientResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MhrFhirClientResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalHealth.MhrFhirClient.MhrFhirClientResource", typeof(MhrFhirClientResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is conditionally mandatory. If the value of &apos;accessType&apos; parameter is &apos;AccessCode&apos;, then a value of &apos;accessCode&apos; parameter has to be sent as well..
        /// </summary>
        internal static string AccessTypeAndAccessCodeError {
            get {
                return ResourceManager.GetString("AccessTypeAndAccessCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;class&apos; or &apos;type&apos; is required.
        /// </summary>
        internal static string ClassOrTypeCodeRequiredError {
            get {
                return ResourceManager.GetString("ClassOrTypeCodeRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null or empty.
        /// </summary>
        internal static string EmptyOrNullError {
            get {
                return ResourceManager.GetString("EmptyOrNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with identifier cannot be combined with any other search parameter.
        /// </summary>
        internal static string IdentifierSearchError {
            get {
                return ResourceManager.GetString("IdentifierSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the IHI number is available then other demographic search criteria is not accepted.
        /// </summary>
        internal static string IhiWithDemographicError {
            get {
                return ResourceManager.GetString("IhiWithDemographicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the IHI number is not available for the patient, you must provide an alternative identifier along with birthdate, gender &amp; family.
        /// </summary>
        internal static string NoIhiError {
            get {
                return ResourceManager.GetString("NoIhiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null.
        /// </summary>
        internal static string NullError {
            get {
                return ResourceManager.GetString("NullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either patientId or patientSearch is mandatory for gaining access to a patient.
        /// </summary>
        internal static string PatientIdOrPatientSearchRequiredError {
            get {
                return ResourceManager.GetString("PatientIdOrPatientSearchRequiredError", resourceCulture);
            }
        }
    }
}
